version: "3.3"


services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 3306:3306
  backend:
    image: iplusaha25/python:latest
    restart: always
    secrets:
      - db-password
    ports:
      - 5000:5000
    networks:
      - backnet
      - frontnet
    depends_on:
      - db
  proxy:
    image: iplusaha25/nginx:latest
    restart: always
    ports:
      - 80:80
    depends_on: 
      - backend
    networks:
      - frontnet
volumes:
  db-data:
secrets:
  db-password:
    file: ../db/password-dev.txt
networks:
  backnet:
  frontnet: