apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: iplusaha25/python:latest
		  name: backend
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /run/secrets/db-password
              name: db-password
      imagePullPolicy: Always
      volumes:
        - name: db-password
          secret:
            items:
              - key: db-password
                path: db-password
            secretName: db-password
