apiVersion: apps/v1
kind: Deployment
metadata:
  name: db 
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  selector:
    matchLabels:
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_DATABASE
              value: example
            - name: MYSQL_ROOT_PASSWORD_FILE
              value: /run/secrets/db-password
          image: mysql:8.0.19
          name: db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /run/secrets/db-password
              name: db-password
            - mountPath: /var/lib/mysql
              name: db-data
      imagePullPolicy: Always
      volumes:
        - name: db-password
		  secret:
            items:
              - key: db-password
                path: db-password
            secretName: db-password
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
