apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - image: iplusaha25/nginx:latest
          name: proxy
		  ports:
            - containerPort: 80
      imagePullPolicy: Always
